name: news_paper
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:


  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

  intl: ^0.17.0



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  rxdart: 0.27.3
  flutter_redux: 0.8.2
  freezed: ^1.1.0
  redux: ^5.0.0
  retrofit: ^3.0.1+1
  dio: 4.0.4
  built_value: ^8.1.4
  json_annotation: ^4.4.0
  redux_epics: ^0.15.1
  freezed_annotation: ^1.1.0
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.20
  google_fonts: ^2.2.0
  firebase_core: ^1.10.0
  firebase_database: ^7.1.2
  firebase_analytics: ^8.2.0
  firebase_auth: ^2.0.0
  google_sign_in: ^5.0.5
 # firebase_messaging: ^9.0.0
  overlay_support: ^1.2.0
  rive: ^0.8.4
  #firebase_crashlytics: ^2.1.1
dependency_overrides:
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^11.1.0
  firebase_messaging_platform_interface: 3.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: ^4.0.1
  build_runner: ^2.1.6
  json_serializable: ^6.1.3
  built_value_generator: ^8.1.4
  injectable: ^1.5.3
  get_it: ^7.2.0
  bottom_animation: ^2.0.0

  flutter_lints: ^1.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/Log1.jpg
     - assets/i18n/en.json
     - assets/i18n/ru.json
     - assets/google_logo.png
     - assets/1534-2994-eye-icon.riv
     - assets/centaur.riv
     - assets/mB.png
     - assets/mB.jpg
     - assets/mb1.png
     - assets/sign-uplogin-animation.riv
     - assets/news.jpg
     - assets/moon.png
     - assets/sun.png
     - assets/sun1.jpg
     - assets/gr.jpg
     - assets/eng.png
     - assets/comand.jpg
     - assets/paper.jpg



  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText-Regular.ttf